/**
 * Generate CSS from @semajsx/tailwind tokens
 *
 * This script extracts CSS from all tailwind tokens used in the docs site
 * and prepends it to the styles file.
 *
 * Usage: bun run generate-css.ts
 */

import { layoutCss } from "./components/Layout";
import { homePageCss } from "./build";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const rootDir = import.meta.dir;

// Collect CSS from all components that export their tokens
const allCss = [
  "/* Generated by @semajsx/tailwind - DO NOT EDIT */",
  layoutCss,
  homePageCss,
  // Add more component CSS exports here as we migrate
].join("\n\n");

// Read the base styles
const baseStylesPath = join(rootDir, "styles-tailwind.css");
const baseStyles = readFileSync(baseStylesPath, "utf-8");

// Combine: tailwind CSS + base styles
const combinedCss = `${allCss}\n\n${baseStyles}`;

// Write to styles.css (the file that build.tsx uses)
const outputPath = join(rootDir, "styles.css");
writeFileSync(outputPath, combinedCss);

console.log("✅ Generated styles.css with tailwind tokens");
console.log(`   - Tailwind CSS: ${allCss.length} bytes`);
console.log(`   - Base styles: ${baseStyles.length} bytes`);
console.log(`   - Total: ${combinedCss.length} bytes`);
